language: julia
notifications:
  email:
    on_success: change
    on_failure: always
os:
- linux
- osx
julia:
- 1.0
- 1.1
- nightly
matrix:
  allow_failures:
  - julia: nightly
after_success:
- julia -e 'VERSION >= v"0.7.0-DEV.5183" && using Pkg; VERSION >= v"0.7.0-DEV.5183"
  || cd(Pkg.dir("SeisIO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder());
  Codecov.submit(Coveralls.process_folder()); '
before_install:
- openssl aes-256-cbc -K $encrypted_faec3b24069b_key -iv $encrypted_faec3b24069b_iv
  -in test/SampleFiles/win32.tar.gz.enc -out test/SampleFiles/win32.tar.gz -d
- tar zxvf test/SampleFiles/win32.tar.gz
