language: julia
notifications:
  email:
    on_success: change
    on_failure: always
codecov: true
coveralls: true
git:
  depth: false
os:
- linux
- osx
- windows
arch:
- x64
# - arm64
julia:
- 1.0
- 1.1
- 1.2
- 1.3
- 1.4
matrix:
  exclude:
    - os: osx
      arch: arm64
    - os: windows
      arch: arm64
  allow_failures:
  - os: windows
  - arch: arm64
  - julia: 1.4
after_success:
- julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
after_failure:
- tail -100 test/runtests.log
before_install:
- cd test
- git clone https://github.com/jpjones76/SeisIO-TestData TestData
- ln -s TestData/SampleFiles/ .
- cd SampleFiles
- openssl aes-256-cbc -K $encrypted_91c8855269b0_key -iv $encrypted_91c8855269b0_iv -in restricted.enc -out restricted.tar.gz -d
- tar zxvf restricted.tar.gz
- rm -f restricted.tar.gz
- cd ../..
before_script:
- julia -e 'println("arch = ", Sys.ARCH)'
script:
- if [[ -a .git/shallow ]]; then git fetch; fi
- julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true);'
